In [1]:
import numpy as np
from scipy import sparse
import scipy.sparse.linalg as sl

from scipy.sparse import coo_matrix
import gudhi as gd
import dmtenergy as dmt


# DMT Energy

This notebook shows some examples of how to compute the DMT-energy of a discrete vector field

### Example 1: DMT energy of discrete vector field (dvf) in a triangle. 

The dvf is given by the pairing of the triangle and an edge


In [2]:
## Build triangle and its associat
st=gd.SimplexTree()
st.insert([0,1,2])
X=dmt.extract_simplices(st)

In [3]:
##dvf given by the pair (Q,WQ)
Q=[1,2]
WQ=[0,1,2]
##Cell complex after collapsing the pair (Q,WQ)
XQ=dmt.extract_xq(X,Q,WQ,1)

In [4]:
## Build boundaries of X
kX=dmt.build_boundaries(X)

In [5]:
##Energy of the DVF
e=dmt.energy(X,XQ,Q,WQ,1,kX)
print(e)

2.0


In [6]:
##If necessary one can compute the bondaries of XQ
boundaries=dmt.build_Q_bounday(XQ,X,Q,WQ,1,kX)

In [7]:
## The chain equivalences psi and phi
psi=dmt.psi(X,XQ,Q,WQ,1,kX)
phi=dmt.phi(X,XQ,Q,WQ,1,kX)
print(phi.toarray())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Example 2: energy of discrete vector field (dvf) in 4 triangls attached by an edge. 
(add figure)
The DVF is a sequence of 4 edges and triangles

In [8]:
## Build the simplicial complex, extract the simplices and its boundary operators
st1=gd.SimplexTree()
st1.insert([0,1,2])
st1.insert([1,2,3])
st1.insert([2,3,4])
st1.insert([3,4,5])


Y=dmt.extract_simplices(st1)
kY=dmt.build_boundaries(Y)

In [9]:
##DVF given by a sequence of edges and triangles
collapses=[[[1,2],[0,1,2]],[[2,3],[1,2,3]],[[3],[1,3]],[[2],[0,2]],[[3,4],[2,3,4]],[[4,5],[3,4,5]]]

dim_collapses=[len(collapses[j][0])-1 for j in range(len(collapses))]


In [10]:
all_psi,all_phi, all_boundaries, all_complexes=dmt.sequence_collpases(Y,kY,collapses,dim_collapses)


In [11]:
##Computet the energy and its matrix
energy,mat_energy=dmt.energy_sequence(all_psi,all_phi)
print(energy)

5.0990195135927845


In [12]:
## Energy matrix
print(np.count_nonzero(np.diag(mat_energy.toarray())))

12


### Example 3: energy of discrete vector field (dvf) in 5 triangls attached by an edge. 
(add figure)
The DVF is a sequence of 4 edges and triangles

In [13]:
## Build the simplicial complex, extract the simplices and its boundary operators
st2=gd.SimplexTree()
st2.insert([0,1,2])
st2.insert([1,2,3])
st2.insert([2,3,4])
st2.insert([3,4,5])
st2.insert([4,5,6])


Z=dmt.extract_simplices(st2)
kZ=dmt.build_boundaries(Z)

In [14]:
##DVF given by a sequence of edges and triangles
#collapsesZ=[[[5,6],[4,5,6]],[[6],[4,6]],[[4,5],[3,4,5]],[[5],[3,5]],[[3,4],[2,3,4]],[[4],[2,4]],[[2,3],[1,2,3]],[[3],[1,3]],[[1,2],[0,1,2]],[[1],[0,1]],[[2],[0,2]]]
collapsesZ=[[[3,4],[2,3,4]],[[4],[2,4]],[[2,3],[1,2,3]],[[3],[1,3]],[[1,2],[0,1,2]],[[1],[0,1]],[[2],[0,2]]]

dim_collapsesZ=[len(collapsesZ[j][0])-1 for j in range(len(collapsesZ))]


In [15]:
all_psiZ,all_phiZ, all_boundariesZ, all_complexesZ=dmt.sequence_collpases(Z,kZ,collapsesZ,dim_collapsesZ)


In [16]:
##Computet the energy and its matrix
energyZ,mat_energyZ=dmt.energy_sequence(all_psiZ,all_phiZ)
print(energyZ**2)

27.0


In [17]:
m=mat_energyZ@mat_energyZ.T


In [18]:
## same example but starting the DVF from the second traingles
##DVF given by a sequence of edges and triangles
collapses1=[[[6],[4,6]],[[4,5],[3,4,5]],[[5],[3,5]],[[3,4],[2,3,4]],[[4],[2,4]],[[2,3],[1,2,3]],[[3],[1,3]],[[1,2],[0,1,2]],[[1],[0,1]],[[2],[0,2]]]
dim_collapses1=[len(collapses1[j][0])-1 for j in range(len(collapses1))]
all_psiZ1,all_phiZ1, all_boundariesZ1, all_complexesZ1=dmt.sequence_collpases(Z,kZ,collapses1,dim_collapses1)


In [19]:
##Computet the energy and its matrix
energy1,mat_energy1=dmt.energy_sequence(all_psiZ1,all_phiZ1)
print(energy1**2)

36.0


## example multiple paths

In [20]:
## Build the simplicial complex, extract the simplices and its boundary operators
st3=gd.SimplexTree()
st3.insert([0,1,2])
st3.insert([0,2,3])
st3.insert([1,2,3])
st3.insert([0,1,6])

#st3.insert([0,1,2])
#st3.insert([0,2,4])
#st3.insert([2,4,3])
#st3.insert([1,2,3])

S=dmt.extract_simplices(st3)
kS=dmt.build_boundaries(S)

In [21]:
collapsesS=[[[1,6],[0,1,6]],[[0,1],[0,1,2]],[[0,2],[0,2,3]],[[1,2],[1,2,3]]]
#collapsesS=[[[0,1],[0,1,2]],[[0,2],[0,2,4]],[[4,2],[2,4,3]],[[1,2],[1,2,3]]]
dim_collapsesS=[len(collapsesS[j][0])-1 for j in range(len(collapsesS))]

In [22]:
all_psiS,all_phiS, all_boundariesS, all_complexesS=dmt.sequence_collpases(S,kS,collapsesS,dim_collapsesS)

In [23]:
##Computet the energy and its matrix
energyS,mat_energyS=dmt.energy_sequence(all_psiS,all_phiS)
print(energyS**2)

17.0


### Preserving Harmonic?

In [226]:
## Build the simplicial complex, extract the simplices and its boundary operators
st4=gd.SimplexTree()
st4.insert([1,2,3])
st4.insert([2,3,4])


st4.insert([0,1])
st4.insert([0,2])



H=dmt.extract_simplices(st4)
kH=dmt.build_boundaries(H)

In [227]:
collapsesH=[[[1,2],[1,2,3]],[[2,3],[2,3,4]]]
dim_collapsesH=[len(collapsesH[j][0])-1 for j in range(len(collapsesH))]

In [228]:
all_psiH,all_phiH, all_boundariesH, all_complexesH=dmt.sequence_collpases(H,kH,collapsesH,dim_collapsesH)

In [229]:
lap1=dmt.build_laplacians(all_boundariesH[0])
lap2=dmt.build_laplacians(all_boundariesH[1])
lap3=dmt.build_laplacians(all_boundariesH[2])

In [230]:
psi=all_psiH[0].toarray()
psi1=psi[len(all_complexesH[1][0]):len(all_complexesH[1][0])+len(all_complexesH[1][1]),len(all_complexesH[0][0]):len(all_complexesH[0][0])+len(all_complexesH[0][1])]
psi1.shape

#psi2=psi[-len(all_complexesH[1][2]):,-len(all_complexesH[0][2]):]

psi_1=all_psiH[1].toarray()
psi11=psi_1[len(all_complexesH[2][0]):len(all_complexesH[2][0])+len(all_complexesH[2][1]),len(all_complexesH[1][0]):len(all_complexesH[1][0])+len(all_complexesH[1][1])]
psi11.shape

(7, 8)

In [231]:
val,vec=sl.eigsh(lap1[1], 2, which='SM')
newh=psi11@psi1@vec[:,0]
#newh=psi1@vec[:,0]

In [232]:
val2,vec2=sl.eigsh(lap2[1], 2, which='SM')

In [233]:
np.linalg.norm(lap3[1]@newh)

3.6568616e-07

In [234]:
psi2

array([[0., 1.]], dtype=float32)

In [235]:
all_boundariesH[1][1].T@psi1

array([[ 0.,  0.,  0., -1.,  0.,  0.,  1., -1.,  1.]], dtype=float32)

In [236]:
psi2@all_boundariesH[0][1].T@vec[:,0]

array([-2.9802322e-08], dtype=float32)

In [237]:
dmt.extract_total_order(H)

{frozenset({0}): 0,
 frozenset({1}): 1,
 frozenset({2}): 2,
 frozenset({3}): 3,
 frozenset({4}): 4,
 frozenset({5}): 5,
 frozenset({0, 1}): 6,
 frozenset({0, 2}): 7,
 frozenset({0, 5}): 8,
 frozenset({1, 2}): 9,
 frozenset({1, 3}): 10,
 frozenset({1, 5}): 11,
 frozenset({2, 3}): 12,
 frozenset({2, 4}): 13,
 frozenset({3, 4}): 14,
 frozenset({1, 2, 3}): 15,
 frozenset({2, 3, 4}): 16}

In [111]:
psid[-1:,-2:]

array([[0., 1.]], dtype=float32)